language: php

php:
  - 5.3
  - 5.6
  - 7.0
  - hhvm

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=3.0.*

sudo: false

before_install:
  - composer selfupdate
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer update --prefer-dist --no-interaction

script: phpunit --coverage-text

notifications:
  email: "contact@uniquelibs.com"

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
    - env: SYMFONY_VERSION=dev-master